### ISSUE TITLE
Compiling/Build Issue

### ISSUE THREAD

**Issue by atefm** [ptran516/siamese-network-ex#1]
The instructions to build the project do not work with Ubuntu. 
"cmake -DDLIB_CMAKE_FILE=$DLIB_ROOT/dlib/cmake .." 

The command above fails with an error "DLIB_DIR must be defined as the path to dlib's root directory."

The following command solves the issue:
cmake -DDLIB_DIR=$DLIB_ROOT -DDLIB_CMAKE_FILE=$DLIB_ROOT/dlib/cmake ..

**Comment by ptran** [comment]
@atefm It looks like I changed the `CMakeLists.txt` without updating the `README.md`.

I don't think you need to use the `-DDLIB_CMAKE_FILE=$DLIB_ROOT/dlib/cmake` flag anymore. Can you check that `cmake -DDLIB_DIR=$DLIB_ROOT ..` works with a fresh build?

If so, can you change the documentation to exclude that flag and also change the flag for the Windows instructions as well. After that, I'll pull in #2.

Thanks!

**Comment by atefm** [comment]
@ptran516 I have just tested the above with fresh build and it compiles successfully. The recommended changes are committed to #2. Thanks!

**Comment by ptran** [comment]
Merged in 👍
